# Generated by Django 2.1 on 2018-08-12 14:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_id', models.CharField(max_length=200)),
                ('form_status', models.CharField(max_length=200)),
                ('requestor_name', models.CharField(max_length=200)),
                ('requestor_email', models.CharField(max_length=200)),
                ('submission_date', models.DateField()),
                ('valid_upto', models.DateField()),
                ('sales_connect', models.IntegerField(default=0)),
                ('form_rfs', models.IntegerField(default=0)),
                ('form_acc_name', models.CharField(max_length=200)),
                ('form_cstmr_id', models.CharField(max_length=200)),
                ('form_sales_id', models.CharField(max_length=200)),
                ('form_aprv_name', models.CharField(max_length=200)),
                ('rsk_rating', models.CharField(max_length=200)),
                ('rsk_region', models.CharField(max_length=200)),
                ('rsk_custom', models.CharField(max_length=200)),
                ('ws_firewall_yes', models.BooleanField(default=False)),
                ('ws_firewall_no', models.BooleanField(default=False)),
                ('ws_hostips_yes', models.BooleanField(default=False)),
                ('ws_hostips_no', models.BooleanField(default=False)),
                ('ws_dacfte_yes', models.BooleanField(default=False)),
                ('ws_dacfte_no', models.BooleanField(default=False)),
                ('coe_endpoint', models.BooleanField(default=False)),
                ('coe_das', models.BooleanField(default=False)),
                ('coe_infra', models.BooleanField(default=False)),
                ('coe_iam', models.BooleanField(default=False)),
                ('coe_sioc', models.BooleanField(default=False)),
                ('eps_malware', models.BooleanField(default=False)),
                ('eps_websec', models.BooleanField(default=False)),
                ('eps_emailsec', models.BooleanField(default=False)),
                ('eps_vulmgmnt', models.BooleanField(default=False)),
                ('eps_dlp', models.BooleanField(default=False)),
                ('esc_bs', models.FloatField(default=None)),
                ('esc_bfte', models.FloatField(default=None)),
                ('esc_b7', models.FloatField(default=None)),
                ('esc_tfte', models.FloatField(default=None)),
                ('esc_b77', models.FloatField(default=None)),
                ('esc_ttfte', models.FloatField(default=None)),
                ('malware_winopn', models.CharField(max_length=200)),
                ('malware_srvcscp', models.CharField(max_length=200)),
                ('servers_vendor', models.CharField(max_length=200)),
                ('servers_antimware', models.IntegerField(default=None)),
                ('servers_noconsole', models.IntegerField(default=None)),
            ],
        ),
    ]
