# Generated by Django 2.1 on 2018-08-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPortal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frm_id', models.UUIDField()),
                ('usr_email', models.CharField(max_length=200)),
                ('frm_stts', models.CharField(max_length=200)),
            ],
        ),
    ]
