# Generated by Django 2.1 on 2018-08-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPortal', '0002_userquote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='coe_das',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='coe_endpoint',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='coe_iam',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='coe_infra',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='coe_sioc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='eps_dlp',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='eps_emailsec',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='eps_malware',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='eps_vulmgmnt',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='eps_websec',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='ws_dacfte_no',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='ws_dacfte_yes',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='ws_firewall_no',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='ws_firewall_yes',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='ws_hostips_no',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='ws_hostips_yes',
            field=models.CharField(max_length=200),
        ),
    ]
