# Generated by Django 2.1 on 2018-08-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPortal', '0003_auto_20180812_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='form_rfs',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='sales_connect',
            field=models.CharField(max_length=200),
        ),
    ]
