# Generated by Django 2.1 on 2018-08-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPortal', '0004_auto_20180812_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='servers_antimware',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='servers_noconsole',
            field=models.CharField(max_length=200),
        ),
    ]
