# Generated by Django 2.1 on 2018-08-13 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webPortal', '0005_auto_20180812_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='trm_cond',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
