# Generated by Django 2.1 on 2018-09-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPortal', '0006_quotation_trm_cond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='coe_das',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='coe_endpoint',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='coe_iam',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='coe_infra',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='coe_sioc',
            field=models.BooleanField(),
        ),
    ]
