# Generated by Django 2.1 on 2018-09-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPortal', '0007_auto_20180902_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='eps_dlp',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='eps_emailsec',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='eps_malware',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='eps_vulmgmnt',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='eps_websec',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='ws_dacfte_no',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='ws_dacfte_yes',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='ws_firewall_no',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='ws_firewall_yes',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='ws_hostips_no',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='ws_hostips_yes',
            field=models.BooleanField(),
        ),
    ]
