# Generated by Django 2.1 on 2018-09-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPortal', '0008_auto_20180902_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='coe_das',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='coe_endpoint',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='coe_iam',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='coe_infra',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='coe_sioc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='eps_dlp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='eps_emailsec',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='eps_malware',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='eps_vulmgmnt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='eps_websec',
            field=models.BooleanField(default=False),
        ),
    ]
