# Generated by Django 2.1 on 2018-09-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPortal', '0009_auto_20180902_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='ws_dacfte_no',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='ws_dacfte_yes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='ws_firewall_no',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='ws_firewall_yes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='ws_hostips_no',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='ws_hostips_yes',
            field=models.BooleanField(default=False),
        ),
    ]
