# Generated by Django 2.1 on 2018-09-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPortal', '0010_auto_20180902_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='esc_b7',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='esc_b77',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='esc_bfte',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='esc_bs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='esc_tfte',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='esc_ttfte',
            field=models.FloatField(default=0.0),
        ),
    ]
