# Generated by Django 2.1 on 2018-09-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPortal', '0011_auto_20180902_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_email', models.CharField(max_length=200)),
                ('usr_name', models.CharField(max_length=200)),
            ],
        ),
    ]
