# Generated by Django 2.1 on 2018-09-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPortal', '0012_approver'),
    ]

    operations = [
        migrations.CreateModel(
            name='userRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_email', models.CharField(max_length=200)),
                ('usr_name', models.CharField(max_length=200)),
                ('usr_role', models.CharField(max_length=200)),
            ],
        ),
    ]
