# Generated by Django 2.1 on 2018-09-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPortal', '0013_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='trm_cond',
            field=models.CharField(max_length=1000),
        ),
    ]
